[package]
name = "kafka-proxy"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
log = "0.4"
fern = "0.6"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde_json = "1"
apache-avro = "0.14"
schema_registry_converter = { version = "3.1", features = ["avro"] }
rdkafka = { version = "0.29", features = ["cmake-build", "ssl", "gssapi", "zstd-pkg-config"] }
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync", "fs", "net"] }
tokio-stream = { version = "0.1", features = ["sync", "io-util"] }
hyper = "0.14"
axum = { version = "0.6", features = ["http1", "http2"] }
coap = "0.12"
coap-lite = "0.9"
opentelemetry = "0.18"
prometheus = "0.13"
opentelemetry-prometheus = "0.11"
