[package]
name = "kafka-proxy"
version = "0.4.0"
edition = "2021"
description = "Service to proxy from various protocols to Kafka"
license = "Apache-2.0"
repository = "https://github.com/mkroli/kafka-proxy"

[profile.release]
strip = "symbols"
opt-level = "s"
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
anyhow = "1"
log = "0.4"
fern = "0.6"
chrono = "0.4"
clap = { version = "4", features = ["derive", "env"] }
serde_json = "1"
apache-avro = "0.14"
schema_registry_converter = { version = "3.1", features = ["avro"] }
rdkafka = { version = "0.29", features = ["cmake-build", "ssl", "gssapi", "zstd-pkg-config"] }
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync", "fs", "net"] }
tokio-stream = { version = "0.1", features = ["sync", "io-util"] }
hyper = "0.14"
axum = { version = "0.6", features = ["headers", "http1", "http2"] }
coap = { version = "0.12", optional = true }
coap-lite = { version = "0.9", optional = true }
opentelemetry = "0.18"
prometheus = "0.13"
opentelemetry-prometheus = "0.11"
posixmq = { version = "1", optional = true }

[dev-dependencies]
reqwest = "0.11"

[features]
default = ["coap", "posixmq"]
coap = ["dep:coap", "dep:coap-lite"]
posixmq = ["dep:posixmq"]
