[env]
CFLAGS = "-isystem /usr/include -isystem /usr/include/x86_64-linux-gnu"
#krb5_cv_attr_constructor_destructor = "yes"
#ac_cv_func_regcomp = "yes"
#ac_cv_printf_positional = "yes"
#ac_cv_gssapi_supports_spnego = "yes"
