name: Build Release

on:
  push:
    tags: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Release Artifact (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            suffix: x86_64-linux-gnu
            cargo: cargo
          - target: x86_64-unknown-linux-musl
            suffix: x86_64-linux-musl
            cargo: cross
          - target: aarch64-unknown-linux-musl
            suffix: aarch64-linux-musl
            cargo: cross
          - target: armv7-unknown-linux-musleabihf
            suffix: armv7-linux-musleabihf
            cargo: cross
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Cross Installation
        run: cargo install cross
        if: ${{ matrix.cargo == 'cross' }}
      - name: Build
        run: |
          ${{ matrix.cargo }} build --release --locked --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/kafka-proxy kafka-proxy_${{ matrix.suffix }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: kafka-proxy_${{ matrix.suffix }}

  container:
    name: Container Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup qemu
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: GitHub Container Registry Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "ghcr.io/mkroli/kafka-proxy:latest"
            "ghcr.io/mkroli/kafka-proxy:${{github.ref_name}}"
