name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install -y libsasl2-dev
    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
    - name: Format
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --check
    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -Dwarnings
