name: GH Release

on:
  push:
    tags: '*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            suffix: x86_64-linux-gnu
            cargo: cargo
          - target: x86_64-unknown-linux-musl
            suffix: x86_64-linux-musl
            cargo: cross
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Cross Installation
        run: cargo install cross
        if: ${{ matrix.cargo == 'cross' }}
      - name: Build
        run: |
          ${{ matrix.cargo }} build --release --locked --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/kafka-proxy kafka-proxy_${{ matrix.suffix }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: kafka-proxy_${{ matrix.suffix }}
